"""Task type enumeration."""

from enum import Enum


class TaskType(str, Enum):
    """Task type enumeration for user tasks.
    
    Note: Database enum uses uppercase values to match PostgreSQL enum type.
    """

    NOTE_TAKING = "NOTE_TAKING"
    ADD_TO_KNOWLEDGE_BASE = "ADD_TO_KNOWLEDGE_BASE"
    QUESTION_ANSWER = "QUESTION_ANSWER"
    CREATE_TODO = "CREATE_TODO"
    EXTRACT_DATA_TO_SHEET = "EXTRACT_DATA_TO_SHEET"
    EXTRACT_DATA_TABLE="EXTRACT_DATA_TABLE"

    ## still to add support
    CREATE_DIAGRAMS = "CREATE_DIAGRAMS"
    CREATE_LOCATION_MAP = "CREATE_LOCATION_MAP"
    COMPARE_SHOPPING_PRICES = "COMPARE_SHOPPING_PRICES"
    FILL_FORM_AUTOMATICALLY="FILL_FORM_AUTOMATICALLY"
    DRAFT_EMAIL="DRAFT_EMAIL"
    CREATE_CALENDAR_EVENT="CREATE_CALENDAR_EVENT"
    AUTO_DOWNLOAD_REPORTS="AUTO_DOWNLOAD_REPORTS"